In [1]:
import numpy as np


In [3]:
W = np.zeros((500,2000))
M = np.zeros((2000,1200))
np.shape(np.matmul(W,M))

(500, 1200)

In [15]:
k_thy = np.linspace(0.0,0.5,500,endpoint=False) + 0.0005

ko = np.loadtxt('k.txt')

In [74]:
k_thy = np.linspace(0.0,0.5,500,endpoint=False) + 0.0005

ko = np.loadtxt('k.txt')

Wmat = np.zeros((5*len(ko),3*len(k_thy)))
w = np.zeros((len(ko),len(k_thy)))

for i,ki in enumerate(ko):
    norm = (1./3.)* ( (k_thy[5*i + 4])**3 - (k_thy[5*i])**3 )
    for j in range(5):
        w[i,5*i + j] = (k_thy[5*i + j]**2) / norm
        
for i,l in enumerate([0,2,4]):
    Wmat[len(ko)*l:len(ko)*l + len(ko),len(k_thy)*i:len(k_thy)*i + len(k_thy)] = w
Wmat

array([[  8.24175824,  74.17582418, 206.04395604, ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 249.99865324,
        251.00468302, 252.01273294]])

In [75]:
Mmat = np.identity(5*len(ko))

In [70]:
# with open('Wmat.txt', 'w', encoding='utf-8') as f:
#     f.write('Hi EveryOne')

mat = np.matrix(Wmat)
    
with open('Wmat.txt','wb') as f:
    for line in mat:
        np.savetxt(f, line, encoding='utf-8')

In [76]:
mat = np.matrix(Mmat)
    
with open('Mmat.txt','wb') as f:
    for line in mat:
        np.savetxt(f, line, encoding='utf-8')

In [77]:
Mtest = np.loadtxt('Mmat.txt')
Mtest

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [78]:
np.matmul(Mtest,Wmat)

array([[  8.24175824,  74.17582418, 206.04395604, ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       ...,
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ...,   0.        ,
          0.        ,   0.        ],
       [  0.        ,   0.        ,   0.        , ..., 249.99865324,
        251.00468302, 252.01273294]])

In [36]:
#test

k_thy = np.linspace(0.0,0.5,9,endpoint=False) + 0.0005
ko = np.linspace(0.0,0.5,3,endpoint=False) + 0.0005

Wmat = np.zeros((5*len(ko),3*len(k_thy)))
w = np.zeros((len(ko),len(k_thy)))

for i,ki in enumerate(ko):
    norm = (1./3.)* ( (k_thy[3*i + 2])**3 - (k_thy[3*i])**3 )
    for j in range(3):
        w[i,3*i + j] = (k_thy[3*i + j]**2) / norm
        
w

array([[5.39434859e-04, 6.78010346e+00, 2.68790467e+01, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.96706315e+00,
        8.81713354e+00, 1.37644027e+01, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 6.57049287e+00, 8.93934421e+00,
        1.16721303e+01]])

In [ ]:
mat = np.matrix(Wmat)
    
with open('Wtest.txt','wb') as f:
    for line in mat:
        np.savetxt(f, line, encoding='utf-8')